<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Inserción de datos correspondientes a la tabla ´distritos´.
        DB::table('distritos')->insert([
            ['id' => 1, 'id_municipio' => 1, 'nombre_distrito' => 'Atiquizaya'],
            ['id' => 2, 'id_municipio' => 1, 'nombre_distrito' => 'El Refugio'],
            ['id' => 3, 'id_municipio' => 1, 'nombre_distrito' => 'San Lorenzo'],
            ['id' => 4, 'id_municipio' => 1, 'nombre_distrito' => 'Turín'],
            ['id' => 5, 'id_municipio' => 2, 'nombre_distrito' => 'Ahuachapán'],
            ['id' => 6, 'id_municipio' => 2, 'nombre_distrito' => 'Apaneca'],
            ['id' => 7, 'id_municipio' => 2, 'nombre_distrito' => 'Concepción de Ataco'],
            ['id' => 8, 'id_municipio' => 2, 'nombre_distrito' => 'Tacuba'],
            ['id' => 9, 'id_municipio' => 3, 'nombre_distrito' => 'Guaymango'],
            ['id' => 10, 'id_municipio' => 3, 'nombre_distrito' => 'Jujutla'],
            ['id' => 11, 'id_municipio' => 3, 'nombre_distrito' => 'San Francisco Menéndez'],
            ['id' => 12, 'id_municipio' => 3, 'nombre_distrito' => 'San Pedro Puxtla'],
            ['id' => 13, 'id_municipio' => 4, 'nombre_distrito' => 'Aguilares'],
            ['id' => 14, 'id_municipio' => 4, 'nombre_distrito' => 'El Paisnal'],
            ['id' => 15, 'id_municipio' => 4, 'nombre_distrito' => 'Guazapa'],
            ['id' => 16, 'id_municipio' => 5, 'nombre_distrito' => 'Apopa'],
            ['id' => 17, 'id_municipio' => 5, 'nombre_distrito' => 'Nejapa'],
            ['id' => 18, 'id_municipio' => 6, 'nombre_distrito' => 'Ilopango'],
            ['id' => 19, 'id_municipio' => 6, 'nombre_distrito' => 'San Martín'],
            ['id' => 20, 'id_municipio' => 6, 'nombre_distrito' => 'Soyapango'],
            ['id' => 21, 'id_municipio' => 6, 'nombre_distrito' => 'Tonacatepeque'],
            ['id' => 22, 'id_municipio' => 7, 'nombre_distrito' => 'Ayutuxtepeque'],
            ['id' => 23, 'id_municipio' => 7, 'nombre_distrito' => 'Mejicanos'],
            ['id' => 24, 'id_municipio' => 7, 'nombre_distrito' => 'San Salvador'],
            ['id' => 25, 'id_municipio' => 7, 'nombre_distrito' => 'Cuscatancingo'],
            ['id' => 26, 'id_municipio' => 7, 'nombre_distrito' => 'Ciudad Delgado'],
            ['id' => 27, 'id_municipio' => 8, 'nombre_distrito' => 'Panchimalco'],
            ['id' => 28, 'id_municipio' => 8, 'nombre_distrito' => 'Rosario de Mora'],
            ['id' => 29, 'id_municipio' => 8, 'nombre_distrito' => 'San Marcos'],
            ['id' => 30, 'id_municipio' => 8, 'nombre_distrito' => 'Santo Tomás'],
            ['id' => 31, 'id_municipio' => 8, 'nombre_distrito' => 'Santiago Texacuangos'],
            ['id' => 32, 'id_municipio' => 9, 'nombre_distrito' => 'Quezaltepeque'],
            ['id' => 33, 'id_municipio' => 9, 'nombre_distrito' => 'San Matías'],
            ['id' => 34, 'id_municipio' => 9, 'nombre_distrito' => 'San Pablo Tacachico'],
            ['id' => 35, 'id_municipio' => 10, 'nombre_distrito' => 'San Juan Opico'],
            ['id' => 36, 'id_municipio' => 10, 'nombre_distrito' => 'Ciudad Arce'],
            ['id' => 37, 'id_municipio' => 11, 'nombre_distrito' => 'Colón'],
            ['id' => 38, 'id_municipio' => 11, 'nombre_distrito' => 'Jayaque'],
            ['id' => 39, 'id_municipio' => 11, 'nombre_distrito' => 'Sacacoyo'],
            ['id' => 40, 'id_municipio' => 11, 'nombre_distrito' => 'Tepecoyo'],
            ['id' => 41, 'id_municipio' => 11, 'nombre_distrito' => 'Talnique'],
            ['id' => 42, 'id_municipio' => 12, 'nombre_distrito' => 'Antiguo Cuscatlán'],
            ['id' => 43, 'id_municipio' => 12, 'nombre_distrito' => 'Huizúcar'],
            ['id' => 44, 'id_municipio' => 12, 'nombre_distrito' => 'Nuevo Cuscatlán'],
            ['id' => 45, 'id_municipio' => 12, 'nombre_distrito' => 'San José Villanueva'],
            ['id' => 46, 'id_municipio' => 12, 'nombre_distrito' => 'Zaragoza'],
            ['id' => 47, 'id_municipio' => 13, 'nombre_distrito' => 'Chiltuipán'],
            ['id' => 48, 'id_municipio' => 13, 'nombre_distrito' => 'Jicalapa'],
            ['id' => 49, 'id_municipio' => 13, 'nombre_distrito' => 'La Libertad'],
            ['id' => 50, 'id_municipio' => 13, 'nombre_distrito' => 'Tamanique'],
            ['id' => 51, 'id_municipio' => 13, 'nombre_distrito' => 'Teotepeque'],
            ['id' => 52, 'id_municipio' => 14, 'nombre_distrito' => 'Comasagua'],
            ['id' => 53, 'id_municipio' => 14, 'nombre_distrito' => 'Santa Tecla'],
            ['id' => 54, 'id_municipio' => 15, 'nombre_distrito' => 'La Palma'],
            ['id' => 55, 'id_municipio' => 15, 'nombre_distrito' => 'Citalá'],
            ['id' => 56, 'id_municipio' => 15, 'nombre_distrito' => 'San Ignacio'],
            ['id' => 57, 'id_municipio' => 16, 'nombre_distrito' => 'Nueva Concepción'],
            ['id' => 58, 'id_municipio' => 16, 'nombre_distrito' => 'Tejutla'],
            ['id' => 59, 'id_municipio' => 16, 'nombre_distrito' => 'La Reina'],
            ['id' => 60, 'id_municipio' => 16, 'nombre_distrito' => 'Agua Caliente'],
            ['id' => 61, 'id_municipio' => 16, 'nombre_distrito' => 'Dulce Nombre de María'],
            ['id' => 62, 'id_municipio' => 16, 'nombre_distrito' => 'El Paraíso'],
            ['id' => 63, 'id_municipio' => 16, 'nombre_distrito' => 'San Francisco Morazán'],
            ['id' => 64, 'id_municipio' => 16, 'nombre_distrito' => 'San Rafael'],
            ['id' => 65, 'id_municipio' => 16, 'nombre_distrito' => 'Santa Rita'],
            ['id' => 66, 'id_municipio' => 16, 'nombre_distrito' => 'San Fernando'],
            ['id' => 67, 'id_municipio' => 17, 'nombre_distrito' => 'Chalatenango'],
            ['id' => 68, 'id_municipio' => 17, 'nombre_distrito' => 'Arcatao'],
            ['id' => 69, 'id_municipio' => 17, 'nombre_distrito' => 'Azacualpa'],
            ['id' => 70, 'id_municipio' => 17, 'nombre_distrito' => 'Comalapa'],
            ['id' => 71, 'id_municipio' => 17, 'nombre_distrito' => 'Concepción Quezaltepeque'],
            ['id' => 72, 'id_municipio' => 17, 'nombre_distrito' => 'El Carrizal'],
            ['id' => 73, 'id_municipio' => 17, 'nombre_distrito' => 'La Laguna'],
            ['id' => 74, 'id_municipio' => 17, 'nombre_distrito' => 'Las Vueltas'],
            ['id' => 75, 'id_municipio' => 17, 'nombre_distrito' => 'Nombre de Jesús'],
            ['id' => 76, 'id_municipio' => 17, 'nombre_distrito' => 'Nueva Trinidad'],
            ['id' => 77, 'id_municipio' => 17, 'nombre_distrito' => 'Ojos de Agua'],
            ['id' => 78, 'id_municipio' => 17, 'nombre_distrito' => 'Potonico'],
            ['id' => 79, 'id_municipio' => 17, 'nombre_distrito' => 'San Antonio de La Cruz'],
            ['id' => 80, 'id_municipio' => 17, 'nombre_distrito' => 'San Antonio Los Ranchos'],
            ['id' => 81, 'id_municipio' => 17, 'nombre_distrito' => 'San Francisco Lempa'],
            ['id' => 82, 'id_municipio' => 17, 'nombre_distrito' => 'San Isidro Labrador'],
            ['id' => 83, 'id_municipio' => 17, 'nombre_distrito' => 'San José Cancasque'],
            ['id' => 84, 'id_municipio' => 17, 'nombre_distrito' => 'San Miguel de Mercedes'],
            ['id' => 85, 'id_municipio' => 17, 'nombre_distrito' => 'San José Las Flores'],
            ['id' => 86, 'id_municipio' => 17, 'nombre_distrito' => 'San Luis del Carmen'],
            ['id' => 87, 'id_municipio' => 18, 'nombre_distrito' => 'Suchitoto'],
            ['id' => 88, 'id_municipio' => 18, 'nombre_distrito' => 'San José Guayabal'],
            ['id' => 89, 'id_municipio' => 18, 'nombre_distrito' => 'Oratorio de Concepción'],
            ['id' => 90, 'id_municipio' => 18, 'nombre_distrito' => 'San Bartolomé Perulapán'],
            ['id' => 91, 'id_municipio' => 18, 'nombre_distrito' => 'San Pedro Perulapán'],
            ['id' => 92, 'id_municipio' => 19, 'nombre_distrito' => 'Cojutepeque'],
            ['id' => 93, 'id_municipio' => 19, 'nombre_distrito' => 'San Rafael Cedros'],
            ['id' => 94, 'id_municipio' => 19, 'nombre_distrito' => 'Candelaria'],
            ['id' => 95, 'id_municipio' => 19, 'nombre_distrito' => 'Monte San Juan'],
            ['id' => 96, 'id_municipio' => 19, 'nombre_distrito' => 'El Carmen'],
            ['id' => 97, 'id_municipio' => 19, 'nombre_distrito' => 'San Cristóbal'],
            ['id' => 98, 'id_municipio' => 19, 'nombre_distrito' => 'Santa Cruz Michapa'],
            ['id' => 99, 'id_municipio' => 19, 'nombre_distrito' => 'San Ramón'],
            ['id' => 100, 'id_municipio' => 19, 'nombre_distrito' => 'El Rosario'],
            ['id' => 101, 'id_municipio' => 19, 'nombre_distrito' => 'Santa Cruz Analquito'],
            ['id' => 102, 'id_municipio' => 19, 'nombre_distrito' => 'Tenancingo'],
            ['id' => 103, 'id_municipio' => 20, 'nombre_distrito' => 'Sensuntepeque'],
            ['id' => 104, 'id_municipio' => 20, 'nombre_distrito' => 'Victoria'],
            ['id' => 105, 'id_municipio' => 20, 'nombre_distrito' => 'Dolores'],
            ['id' => 106, 'id_municipio' => 20, 'nombre_distrito' => 'Guacotecti'],
            ['id' => 107, 'id_municipio' => 20, 'nombre_distrito' => 'San Isidro'],
            ['id' => 108, 'id_municipio' => 21, 'nombre_distrito' => 'Ilobasco'],
            ['id' => 109, 'id_municipio' => 21, 'nombre_distrito' => 'Tejutepeque'],
            ['id' => 110, 'id_municipio' => 21, 'nombre_distrito' => 'Jutiapa'],
            ['id' => 111, 'id_municipio' => 21, 'nombre_distrito' => 'Cinquera'],
            ['id' => 112, 'id_municipio' => 22, 'nombre_distrito' => 'Cuyultitán'],
            ['id' => 113, 'id_municipio' => 22, 'nombre_distrito' => 'Olocuilta'],
            ['id' => 114, 'id_municipio' => 22, 'nombre_distrito' => 'San Juan Talpa'],
            ['id' => 115, 'id_municipio' => 22, 'nombre_distrito' => 'San Luis Talpa'],
            ['id' => 116, 'id_municipio' => 22, 'nombre_distrito' => 'San Pedro Masahuat'],
            ['id' => 117, 'id_municipio' => 22, 'nombre_distrito' => 'Tapalhuaca'],
            ['id' => 118, 'id_municipio' => 22, 'nombre_distrito' => 'San Francisco Chinameca'],
            ['id' => 119, 'id_municipio' => 23, 'nombre_distrito' => 'El Rosario'],
            ['id' => 120, 'id_municipio' => 23, 'nombre_distrito' => 'Jerusalén'],
            ['id' => 121, 'id_municipio' => 23, 'nombre_distrito' => 'Mercedes La Ceiba'],
            ['id' => 122, 'id_municipio' => 23, 'nombre_distrito' => 'Paraíso de Osorio'],
            ['id' => 123, 'id_municipio' => 23, 'nombre_distrito' => 'San Antonio Masahuat'],
            ['id' => 124, 'id_municipio' => 23, 'nombre_distrito' => 'San Emigdio'],
            ['id' => 125, 'id_municipio' => 23, 'nombre_distrito' => 'San Juan Tepezontes'],
            ['id' => 126, 'id_municipio' => 23, 'nombre_distrito' => 'San Luis La Herradura'],
            ['id' => 127, 'id_municipio' => 23, 'nombre_distrito' => 'San Miguel Tepezontes'],
            ['id' => 128, 'id_municipio' => 23, 'nombre_distrito' => 'San Pedro Nonualco'],
            ['id' => 129, 'id_municipio' => 23, 'nombre_distrito' => 'Santa María Ostuma'],
            ['id' => 130, 'id_municipio' => 23, 'nombre_distrito' => 'Santiago Nonualco'],
            ['id' => 131, 'id_municipio' => 24, 'nombre_distrito' => 'San Juan Nonualco'],
            ['id' => 132, 'id_municipio' => 24, 'nombre_distrito' => 'San Rafael Obrajuelo'],
            ['id' => 133, 'id_municipio' => 24, 'nombre_distrito' => 'Zacatecoluca'],
            ['id' => 134, 'id_municipio' => 25, 'nombre_distrito' => 'Anamorós'],
            ['id' => 135, 'id_municipio' => 25, 'nombre_distrito' => 'Bolivar'],
            ['id' => 136, 'id_municipio' => 25, 'nombre_distrito' => 'Concepción de Oriente'],
            ['id' => 137, 'id_municipio' => 25, 'nombre_distrito' => 'El Sauce'],
            ['id' => 138, 'id_municipio' => 25, 'nombre_distrito' => 'Lislique'],
            ['id' => 139, 'id_municipio' => 25, 'nombre_distrito' => 'Nueva Esparta'],
            ['id' => 140, 'id_municipio' => 25, 'nombre_distrito' => 'Pasaquina'],
            ['id' => 141, 'id_municipio' => 25, 'nombre_distrito' => 'Polorós'],
            ['id' => 142, 'id_municipio' => 25, 'nombre_distrito' => 'San José La Fuente'],
            ['id' => 143, 'id_municipio' => 25, 'nombre_distrito' => 'Santa Rosa de Lima'],
            ['id' => 144, 'id_municipio' => 26, 'nombre_distrito' => 'Conchagua'],
            ['id' => 145, 'id_municipio' => 26, 'nombre_distrito' => 'El Carmen'],
            ['id' => 146, 'id_municipio' => 26, 'nombre_distrito' => 'Intipucá'],
            ['id' => 147, 'id_municipio' => 26, 'nombre_distrito' => 'La Unión'],
            ['id' => 148, 'id_municipio' => 26, 'nombre_distrito' => 'Meanguera del Golfo'],
            ['id' => 149, 'id_municipio' => 26, 'nombre_distrito' => 'San Alejo'],
            ['id' => 150, 'id_municipio' => 26, 'nombre_distrito' => 'Yayantique'],
            ['id' => 151, 'id_municipio' => 26, 'nombre_distrito' => 'Yucuaiquín'],
            ['id' => 152, 'id_municipio' => 27, 'nombre_distrito' => 'Santiago de María'],
            ['id' => 153, 'id_municipio' => 27, 'nombre_distrito' => 'Alegría'],
            ['id' => 154, 'id_municipio' => 27, 'nombre_distrito' => 'Berlín'],
            ['id' => 155, 'id_municipio' => 27, 'nombre_distrito' => 'Mercedes Umana'],
            ['id' => 156, 'id_municipio' => 27, 'nombre_distrito' => 'Jucuapa'],
            ['id' => 157, 'id_municipio' => 27, 'nombre_distrito' => 'El Triunfo'],
            ['id' => 158, 'id_municipio' => 27, 'nombre_distrito' => 'Estanzuelas'],
            ['id' => 159, 'id_municipio' => 27, 'nombre_distrito' => 'San Buenaventura'],
            ['id' => 160, 'id_municipio' => 27, 'nombre_distrito' => 'Nueva Granada'],
            ['id' => 161, 'id_municipio' => 28, 'nombre_distrito' => 'Usulután'],
            ['id' => 162, 'id_municipio' => 28, 'nombre_distrito' => 'Jucuarán'],
            ['id' => 163, 'id_municipio' => 28, 'nombre_distrito' => 'San Dionisio'],
            ['id' => 164, 'id_municipio' => 28, 'nombre_distrito' => 'Concepción Batres'],
            ['id' => 165, 'id_municipio' => 28, 'nombre_distrito' => 'Santa María'],
            ['id' => 166, 'id_municipio' => 28, 'nombre_distrito' => 'Ozatlán'],
            ['id' => 167, 'id_municipio' => 28, 'nombre_distrito' => 'Tecapán'],
            ['id' => 168, 'id_municipio' => 28, 'nombre_distrito' => 'Santa Elena'],
            ['id' => 169, 'id_municipio' => 28, 'nombre_distrito' => 'California'],
            ['id' => 170, 'id_municipio' => 28, 'nombre_distrito' => 'Ereguayquín'],
            ['id' => 171, 'id_municipio' => 29, 'nombre_distrito' => 'Jiquilisco'],
            ['id' => 172, 'id_municipio' => 29, 'nombre_distrito' => 'Puerto El Triunfo'],
            ['id' => 173, 'id_municipio' => 29, 'nombre_distrito' => 'San Agustín'],
            ['id' => 174, 'id_municipio' => 29, 'nombre_distrito' => 'San Francisco Javier'],
            ['id' => 175, 'id_municipio' => 30, 'nombre_distrito' => 'Juayúa'],
            ['id' => 176, 'id_municipio' => 30, 'nombre_distrito' => 'Nahuizalco'],
            ['id' => 177, 'id_municipio' => 30, 'nombre_distrito' => 'Salcoatitán'],
            ['id' => 178, 'id_municipio' => 30, 'nombre_distrito' => 'Santa Catarina Masahuat'],
            ['id' => 179, 'id_municipio' => 31, 'nombre_distrito' => 'Sonsonate'],
            ['id' => 180, 'id_municipio' => 31, 'nombre_distrito' => 'Sonzacate'],
            ['id' => 181, 'id_municipio' => 31, 'nombre_distrito' => 'Nahulingo'],
            ['id' => 182, 'id_municipio' => 31, 'nombre_distrito' => 'San Antonio del Monte'],
            ['id' => 183, 'id_municipio' => 31, 'nombre_distrito' => 'Santo Domingo de Guzmán'],
            ['id' => 184, 'id_municipio' => 32, 'nombre_distrito' => 'Izalco'],
            ['id' => 185, 'id_municipio' => 32, 'nombre_distrito' => 'Armenia'],
            ['id' => 186, 'id_municipio' => 32, 'nombre_distrito' => 'Caluco'],
            ['id' => 187, 'id_municipio' => 32, 'nombre_distrito' => 'San Julián'],
            ['id' => 188, 'id_municipio' => 32, 'nombre_distrito' => 'Cuisnahuat'],
            ['id' => 189, 'id_municipio' => 32, 'nombre_distrito' => 'Santa Isabel Ishuatán'],
            ['id' => 190, 'id_municipio' => 33, 'nombre_distrito' => 'Acajutla'],
            ['id' => 191, 'id_municipio' => 34, 'nombre_distrito' => 'Masahuat'],
            ['id' => 192, 'id_municipio' => 34, 'nombre_distrito' => 'Metapán'],
            ['id' => 193, 'id_municipio' => 34, 'nombre_distrito' => 'Santa Rosa Guachipilín'],
            ['id' => 194, 'id_municipio' => 34, 'nombre_distrito' => 'Texistepeque'],
            ['id' => 195, 'id_municipio' => 35, 'nombre_distrito' => 'Santa Ana'],
            ['id' => 196, 'id_municipio' => 36, 'nombre_distrito' => 'Coatepeque'],
            ['id' => 197, 'id_municipio' => 36, 'nombre_distrito' => 'El Congo'],
            ['id' => 198, 'id_municipio' => 37, 'nombre_distrito' => 'Candelaria de la Frontera'],
            ['id' => 199, 'id_municipio' => 37, 'nombre_distrito' => 'Chalchuapa'],
            ['id' => 200, 'id_municipio' => 37, 'nombre_distrito' => 'El Porvenir'],
            ['id' => 201, 'id_municipio' => 37, 'nombre_distrito' => 'San Antonio Pajonal'],
            ['id' => 202, 'id_municipio' => 37, 'nombre_distrito' => 'San Sebastián Salitrillo'],
            ['id' => 203, 'id_municipio' => 37, 'nombre_distrito' => 'Santiago de La Frontera'],
            ['id' => 204, 'id_municipio' => 38, 'nombre_distrito' => 'Apastepeque'],
            ['id' => 205, 'id_municipio' => 38, 'nombre_distrito' => 'Santa Clara'],
            ['id' => 206, 'id_municipio' => 38, 'nombre_distrito' => 'San Ildefonso'],
            ['id' => 207, 'id_municipio' => 38, 'nombre_distrito' => 'San Esteban Catarina'],
            ['id' => 208, 'id_municipio' => 38, 'nombre_distrito' => 'San Sebastián'],
            ['id' => 209, 'id_municipio' => 38, 'nombre_distrito' => 'San Lorenzo'],
            ['id' => 210, 'id_municipio' => 38, 'nombre_distrito' => 'Santo Domingo'],
            ['id' => 211, 'id_municipio' => 39, 'nombre_distrito' => 'San Vicente'],
            ['id' => 212, 'id_municipio' => 39, 'nombre_distrito' => 'Guadalupe'],
            ['id' => 213, 'id_municipio' => 39, 'nombre_distrito' => 'Verapaz'],
            ['id' => 214, 'id_municipio' => 39, 'nombre_distrito' => 'Tepetitán'],
            ['id' => 215, 'id_municipio' => 39, 'nombre_distrito' => 'Tecoluca'],
            ['id' => 216, 'id_municipio' => 39, 'nombre_distrito' => 'San Cayetano Istepeque'],
            ['id' => 217, 'id_municipio' => 40, 'nombre_distrito' => 'Ciudad Barrios'],
            ['id' => 218, 'id_municipio' => 40, 'nombre_distrito' => 'Sesori'],
            ['id' => 219, 'id_municipio' => 40, 'nombre_distrito' => 'Nuevo Edén de San Juan'],
            ['id' => 220, 'id_municipio' => 40, 'nombre_distrito' => 'San Gerardo'],
            ['id' => 221, 'id_municipio' => 40, 'nombre_distrito' => 'San Luis de La Reina'],
            ['id' => 222, 'id_municipio' => 40, 'nombre_distrito' => 'Carolina'],
            ['id' => 223, 'id_municipio' => 40, 'nombre_distrito' => 'San Antonio del Mosco'],
            ['id' => 224, 'id_municipio' => 40, 'nombre_distrito' => 'Chapeltique'],
            ['id' => 225, 'id_municipio' => 41, 'nombre_distrito' => 'San Miguel'],
            ['id' => 226, 'id_municipio' => 41, 'nombre_distrito' => 'Comacarán'],
            ['id' => 227, 'id_municipio' => 41, 'nombre_distrito' => 'Uluazapa'],
            ['id' => 228, 'id_municipio' => 41, 'nombre_distrito' => 'Moncagua'],
            ['id' => 229, 'id_municipio' => 41, 'nombre_distrito' => 'Quelepa'],
            ['id' => 230, 'id_municipio' => 41, 'nombre_distrito' => 'Chirilagua'],
            ['id' => 231, 'id_municipio' => 42, 'nombre_distrito' => 'Chinameca'],
            ['id' => 232, 'id_municipio' => 42, 'nombre_distrito' => 'Nueva Guadalupe'],
            ['id' => 233, 'id_municipio' => 42, 'nombre_distrito' => 'Lolotique'],
            ['id' => 234, 'id_municipio' => 42, 'nombre_distrito' => 'San Jorge'],
            ['id' => 235, 'id_municipio' => 42, 'nombre_distrito' => 'San Rafael Oriente'],
            ['id' => 236, 'id_municipio' => 42, 'nombre_distrito' => 'El Tránsito'],
            ['id' => 237, 'id_municipio' => 43, 'nombre_distrito' => 'Arambala'],
            ['id' => 238, 'id_municipio' => 43, 'nombre_distrito' => 'Cacaopera'],
            ['id' => 239, 'id_municipio' => 43, 'nombre_distrito' => 'Corinto'],
            ['id' => 240, 'id_municipio' => 43, 'nombre_distrito' => 'El Rosario'],
            ['id' => 241, 'id_municipio' => 43, 'nombre_distrito' => 'Joateca'],
            ['id' => 242, 'id_municipio' => 43, 'nombre_distrito' => 'Jocoaitique'],
            ['id' => 243, 'id_municipio' => 43, 'nombre_distrito' => 'Meanguera'],
            ['id' => 244, 'id_municipio' => 43, 'nombre_distrito' => 'Perquín'],
            ['id' => 245, 'id_municipio' => 43, 'nombre_distrito' => 'San Fernando'],
            ['id' => 246, 'id_municipio' => 43, 'nombre_distrito' => 'San Isidro'],
            ['id' => 247, 'id_municipio' => 43, 'nombre_distrito' => 'Torola'],
            ['id' => 248, 'id_municipio' => 44, 'nombre_distrito' => 'Chilanga'],
            ['id' => 249, 'id_municipio' => 44, 'nombre_distrito' => 'Delicias de Concepción'],
            ['id' => 250, 'id_municipio' => 44, 'nombre_distrito' => 'El Divisadero'],
            ['id' => 251, 'id_municipio' => 44, 'nombre_distrito' => 'Gualococti'],
            ['id' => 252, 'id_municipio' => 44, 'nombre_distrito' => 'Guatajiagua'],
            ['id' => 253, 'id_municipio' => 44, 'nombre_distrito' => 'Jocoro'],
            ['id' => 254, 'id_municipio' => 44, 'nombre_distrito' => 'Lolotiquillo'],
            ['id' => 255, 'id_municipio' => 44, 'nombre_distrito' => 'Osicala'],
            ['id' => 256, 'id_municipio' => 44, 'nombre_distrito' => 'San Carlos'],
            ['id' => 257, 'id_municipio' => 44, 'nombre_distrito' => 'San Francisco Gotera'],
            ['id' => 258, 'id_municipio' => 44, 'nombre_distrito' => 'San Simón'],
            ['id' => 259, 'id_municipio' => 44, 'nombre_distrito' => 'Sensembra'],
            ['id' => 260, 'id_municipio' => 44, 'nombre_distrito' => 'Sociedad'],
            ['id' => 261, 'id_municipio' => 44, 'nombre_distrito' => 'Yamabal'],
            ['id' => 262, 'id_municipio' => 44, 'nombre_distrito' => 'Yoloaiquín'],
        ]);
    }
}
